const { withSettingsGradle, withDangerousMod } = require('@expo/config-plugins')
const fs = require('fs')
const path = require('path')

// Gradle 9.0.0 (the version this template's CNG pins in
// android/gradle/wrapper/gradle-wrapper.properties) can only be paired with
// an alpha-quality AGP (9.5.0-alpha02 at the time this plugin was written).
// That AGP's prefab/CMake "configureCMakeDebug" step misclassifies the JDK's
// JEP 472 "restricted native access" warning banner as a fatal build error
// (com.android.build.gradle.tasks.GeneratePrefabPackagesKt.reportErrors
// treats any unrecognized stderr line from the prefab subprocess as fatal).
// The JBR bundled with Android Studio (used as JAVA_HOME to drive Gradle
// here) is a modern JDK that prints this warning; there's no older JDK on a
// stock Android Studio install to fall back to. See
// docs/notes/api-divergences.md (Task 2) for the full investigation.
//
// Fix: make Gradle's *daemon* run under an auto-provisioned JDK 21 instead
// of JAVA_HOME, via Gradle 9's Daemon JVM criteria feature
// (`gradlew updateDaemonJvm`). That needs two things CNG regenerates from
// scratch on every prebuild:
//   1. a toolchain-download resolver plugin in the root settings.gradle
//      (auto-provisioning has nowhere to download a JDK from otherwise)
//   2. gradle/gradle-daemon-jvm.properties requesting that JDK
// This config plugin re-applies both so a fresh clone + `expo run:android`
// keeps working without re-running `updateDaemonJvm` by hand.

const FOOJAY_PLUGIN_LINE =
  'id("org.gradle.toolchains.foojay-resolver-convention").version("1.0.0")'

// Captured verbatim from a real `./gradlew updateDaemonJvm --jvm-version=21
// --jvm-vendor=adoptium` run against this project. The toolchainUrl.* lines
// are foojay's own stable per-platform redirect ids, resolved once and
// baked in for reproducibility (same as `updateDaemonJvm` does by default).
const DAEMON_JVM_PROPERTIES = `#This file is generated by updateDaemonJvm
toolchainUrl.FREE_BSD.AARCH64=https\\://api.foojay.io/disco/v3.0/ids/cb205e54cea236622eee3d62deb2c768/redirect
toolchainUrl.FREE_BSD.X86_64=https\\://api.foojay.io/disco/v3.0/ids/452acd2202c1005abda962c6dae7fc5f/redirect
toolchainUrl.LINUX.AARCH64=https\\://api.foojay.io/disco/v3.0/ids/cb205e54cea236622eee3d62deb2c768/redirect
toolchainUrl.LINUX.X86_64=https\\://api.foojay.io/disco/v3.0/ids/452acd2202c1005abda962c6dae7fc5f/redirect
toolchainUrl.MAC_OS.AARCH64=https\\://api.foojay.io/disco/v3.0/ids/faa59212208d027d066d1bbe337c5da5/redirect
toolchainUrl.MAC_OS.X86_64=https\\://api.foojay.io/disco/v3.0/ids/adf5b89d64773eff73f900e61dd2d632/redirect
toolchainUrl.UNIX.AARCH64=https\\://api.foojay.io/disco/v3.0/ids/cb205e54cea236622eee3d62deb2c768/redirect
toolchainUrl.UNIX.X86_64=https\\://api.foojay.io/disco/v3.0/ids/452acd2202c1005abda962c6dae7fc5f/redirect
toolchainUrl.WINDOWS.AARCH64=https\\://api.foojay.io/disco/v3.0/ids/fb93b09f091ba9740dea6fe657f3c66a/redirect
toolchainUrl.WINDOWS.X86_64=https\\://api.foojay.io/disco/v3.0/ids/ccc3884e65cd85bb71a09d2223c77229/redirect
toolchainVendor=ADOPTIUM
toolchainVersion=21
`

function withFoojayResolver(config) {
  return withSettingsGradle(config, (config) => {
    if (!config.modResults.contents.includes('foojay-resolver-convention')) {
      config.modResults.contents = config.modResults.contents.replace(
        'plugins {',
        `plugins {\n  ${FOOJAY_PLUGIN_LINE}`
      )
    }
    return config
  })
}

function withDaemonJvmProperties(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const gradleDir = path.join(config.modRequest.platformProjectRoot, 'gradle')
      fs.mkdirSync(gradleDir, { recursive: true })
      fs.writeFileSync(
        path.join(gradleDir, 'gradle-daemon-jvm.properties'),
        DAEMON_JVM_PROPERTIES
      )
      return config
    }
  ])
}

module.exports = function withGradleJvmFix(config) {
  config = withFoojayResolver(config)
  config = withDaemonJvmProperties(config)
  return config
}
